sources:
  - name: polkachu
    type: websocket
    url: wss://juno-testnet-rpc.polkachu.com/websocket
  - name: polkachu
    type: polling
    url: https://juno-testnet-rpc.polkachu.com

filters:
  # NOTE: All filter values are regular expressions, try it out!
  # - type: message
  #   attributes:
  #     - key: action
  #       value: MsgExecuteContract
